### ISSUE TITLE
Need conda deps

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/tool-bank-golm-lib_search#1]
I'm working on it!
# PERL compilator / libraries :
- [X] $ perl -v #This is perl, v5.18.2 built for x86_64-linux-gnu-thread-multi
## libs CORE PERL :
- [X] use strict ;
- [X] use warnings ;
- [X] use Carp qw (cluck croak carp) ;
- [X] use Exporter ;
- [X] use Data::Dumper ;
- [X] use Getopt::Long ;
- [X] use FindBin ;
## libs CPAN PERL :
- [X] $ perl -e 'use SOAP::Lite +trace => [qw (debug)] ;'
- [ ] $ perl -e 'use Excel::Writer::XLSX ;'
- [X] $ perl -e 'use JSON ;'
- [X] $ perl -e 'use HTML::Template ;'
- [X] use List::MoreUtils qw(uniq);

**Comment by lecorguille** [comment]
- [X]  $ perl -e 'use Excel::Writer::XLSX ;'

PR on bioconda in progress: https://github.com/bioconda/bioconda-recipes/pull/2005

**Comment by lecorguille** [comment]
@fgiacomoni I can't find any script which ask for `use Excel::Writer::XLSX ;`
Is it still a dependency?

**Comment by lecorguille** [comment]
Active branch dedicated to this task: https://github.com/workflow4metabolomics/tool-bank-golm-lib_search/tree/conda

**Comment by fgiacomoni** [comment]
Nope ! It was used in a deprecated version but it will be usefull for later so don't worried about your work (many tahnks) : this bioconda dependency will be used in future version of some annotation tools (I waiting for technical discussion about the management of the binary xlsx format in Galaxy)

**Comment by lecorguille** [comment]
PR Merge on bioconda
According to https://github.com/workflow4metabolomics/tool-bank-golm-lib_search/blob/master/_README.txt, all deps seem available through conda

**Comment by lecorguille** [comment]
An issue with `use List::MoreUtils qw(uniq);` (https://github.com/workflow4metabolomics/tool-bank-golm-lib_search/issues/2) is caused by the conda package perl-excel-writer-xlsx (https://github.com/bioconda/bioconda-recipes/pull/2102) which didn't use perl-theaded as dependency.

So I disabled perl-excel-writer-xlsx for the moment and it works!

**Comment by fgiacomoni** [comment]
Thank for all Gildas
