### ISSUE TITLE
Cannot enter 'none' for the Alkane RI.

### ISSUE THREAD

**Issue by lecorguille** [workflow4metabolomics/tool-bank-golm-lib_search#5]
Original Issue: https://github.com/galaxyproject/galaxy/issues/8064

> When using the Golm Annotation tool, in the GC-MS pipeline, you cannot enter 'none' for the Alkane RI.

Ping: @fgiacomoni, @yguitton

**Comment by fgiacomoni** [comment]
I saw this question asked on galaxy.eu instance...
the algorithm behind Golm db search includes alkane RI as input data. So it not possible to unset this parameter or to set to none. There is no logic todo this using Golm Db.

**Comment by lecorguille** [comment]
> So it not possible to unset this parameter or to set to none.

Can we explicit that in the help to avoid confusion?
